export const PATH = {
  HOME: '/',
  LOGIN: '/sign-in',
  SIGNUP: '/sign-up',
  FORGOT_PASSWORD: '/forgot-password',
  RECOVERY: '/recovery',
  RECOVERY_RESENDING: '/recovery-resending',
  REGISTRATION_CONFIRMATION: '/registration-confirmation',
  REGISTRATION_EMAIL_RESENDING: '/registration-email-resending',
  TERMS_OF_SERVICE: '/sign-up/terms-of-service',
  PRIVACY_POLICY: '/sign-up/privacy-policy',
  NEW_PASSWORD: '/new-password',
  USERS: {
    PROFILE: '/users/profile',
    PROFILE_USERID: (userId: number) => `/users/profile/${userId}`,
    PROFILE_SETTINGS: (userId: number) => `/users/profile/${userId}/settings`,
  },

  FEED: '/users/feed',
  POSTS: '/posts',
  MESSENGER: '/messenger',
  SEARCH: '/search',
  STATISTICS: '/statistics',
  FAVORITES: '/favorites',
}
