import '@radix-ui/themes/styles.css'
import './styles/globals.css'
import 'cropperjs/dist/cropper.css'
import '../shared/config/i18n/i18n'
import 'swiper/css'
import 'swiper/css/navigation'
import 'swiper/css/pagination'
import type { Metadata } from 'next'
import { Theme } from '@radix-ui/themes'
import { AuthInitializer } from './providers'
import ModalHost from '@/widgets/ModalHost/ModalHost'
import StoreProvider from '@/store/StoreProvider'
import HeaderSidebarProvider from '@/widgets/header/HeaderSidebarProvider'
export const metadata: Metadata = {
  title: 'Inctagram',
  description: 'Generated by samurai iron team',
  icons: {
    icon: '/logo.png',
  },
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`antialiased overflow-hidden`} suppressHydrationWarning>
        <StoreProvider>
          <Theme>
            <AuthInitializer>
              <HeaderSidebarProvider>
                {children}
                <ModalHost />
              </HeaderSidebarProvider>
            </AuthInitializer>
          </Theme>
        </StoreProvider>
      </body>
    </html>
  )
}
