import type { Metadata } from "next"
import { Inter } from "next/font/google"
import '@radix-ui/themes/styles.css'
import './styles/globals.css'
import StoreProvider from '@/store/StoreProvider'
import ThemeProvider from '@/shared/config/theme/theme-provider'

// const inter = Inter({
//   variable: '--font-inter',
//   subsets: ['latin'],
// })
// ${inter.variable}

export const metadata: Metadata = {
  title: 'Inctagram',
  description: 'Generated by samurai iron team',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <StoreProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  )
}
