import type { Metadata } from 'next'
import '@radix-ui/themes/styles.css'
import './styles/globals.css'
import StoreProvider from '@/store/StoreProvider'
import { Theme } from '@radix-ui/themes'
import HeaderSidebarProvider from '@/widgets/header/HeaderSidebarProvider'
import '../shared/config/i18n/i18n'
import { AuthInitializer } from '@/shared/providers/AuthInitializer'

export const metadata: Metadata = {
  title: 'Inctagram',
  description: 'Generated by samurai iron team',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <StoreProvider>
          <AuthInitializer>
            <Theme>
              <HeaderSidebarProvider>{children}</HeaderSidebarProvider>
            </Theme>
          </AuthInitializer>
        </StoreProvider>
      </body>
    </html>
  )
}
